// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh_5G_mN9-ObQ6P0N5UQjIX_aZKb9YhQA',
    appId: '1:103223415683:web:ab313581351da759c29cb6',
    messagingSenderId: '103223415683',
    projectId: 'aferconpay1',
    authDomain: 'aferconpay1.firebaseapp.com',
    storageBucket: 'aferconpay1.firebasestorage.app',
    measurementId: 'G-NL8QGTR895',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJH65ODUdDLwEKC1yCnMS-h5KMCxgPDaE',
    appId: '1:103223415683:android:c63f7fb8dc4dac14c29cb6',
    messagingSenderId: '103223415683',
    projectId: 'aferconpay1',
    storageBucket: 'aferconpay1.firebasestorage.app',
  );

}